import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "../../components/pages/Header";
import Footer from "../../components/pages/Footer";
import Home from "../../components/pages/Home";
import About from "../../components/pages/About";
import Contact from "../../components/pages/Contact";
import "animate.css";
import Gallery from "../../components/pages/Gallery";
import Photos from "../../components/pages/Photos";
import Kepala from "../../components/pages/Kepala";

const inter = Inter({ subsets: ["latin"] });

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Web Desa Kalukuang</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/images/logo desa update.png" />
      </Head>

      <Header />

      <section className="mb-14 block">
        {/* Home Section */}
        <section id="home-section" className="relative px-3">
          <Home />
        </section>

        {/* About Section */}
        <section id="about-section" className="px-10 py-10 lg:px-20 lg:py-20">
          <About />
        </section>

        {/* Kepala Section */}
        <section id="kepala-section" className="px-10 py-10 lg:px-20 lg:py-20">
          <Kepala />
        </section>

        {/* Gallery Section */}
        <section
          id="gallery-section"
          className="px-10 py-10 lg:px-20 lg:py-20"
        >
          <Gallery />
        </section>

        {/* Photos Section */}
        <section
          id="photos-section"
          className="px-10 py-10 lg:px-20 lg:py-20"
        >
          <Photos />
        </section>

        {/* Contact Section */}
        <section id="contact-section" className="px-10 py-10 lg:px-20 lg:py-20">
          <Contact />
        </section>
      </section>

      <Footer />
    </>
  );
}
